import * as React from 'react';
import { Command as CommandPrimitive } from 'cmdk';
import { MagnifyingGlass as Search } from '@phosphor-icons/react';
import { cn } from '@/src/lib/utils';

export const Command = React.forwardRef<React.ElementRef<typeof CommandPrimitive>, React.ComponentPropsWithoutRef<typeof CommandPrimitive>>(({ className, ...props }, ref) => <CommandPrimitive ref={ref} className={cn('flex h-full w-full flex-col overflow-hidden rounded-md bg-[var(--popover)] text-[var(--popover-foreground)]', className)} {...props} />);
Command.displayName = CommandPrimitive.displayName;
export const CommandDialog = ({ children, ...props }: React.ComponentProps<typeof CommandPrimitive>) => <CommandPrimitive {...props}>{children}</CommandPrimitive>;
export const CommandInput = React.forwardRef<React.ElementRef<typeof CommandPrimitive.Input>, React.ComponentPropsWithoutRef<typeof CommandPrimitive.Input> & { containerClassName?: string }>(({ className, containerClassName, ...props }, ref) => <div className={cn('flex h-10 items-center gap-2 border-b border-[var(--border)] px-3', containerClassName)}><Search className="size-4 shrink-0 text-[var(--muted-foreground)]" /><CommandPrimitive.Input ref={ref} className={cn('flex h-full w-full bg-transparent text-[length:var(--text-xs)] outline-none placeholder:text-[var(--muted-foreground)]', className)} {...props} /></div>);
CommandInput.displayName = CommandPrimitive.Input.displayName;
export const CommandList = React.forwardRef<React.ElementRef<typeof CommandPrimitive.List>, React.ComponentPropsWithoutRef<typeof CommandPrimitive.List>>(({ className, ...props }, ref) => <CommandPrimitive.List ref={ref} className={cn('max-h-72 overflow-y-auto overflow-x-hidden p-1', className)} {...props} />);
CommandList.displayName = CommandPrimitive.List.displayName;
export const CommandEmpty = React.forwardRef<React.ElementRef<typeof CommandPrimitive.Empty>, React.ComponentPropsWithoutRef<typeof CommandPrimitive.Empty>>(({ className, ...props }, ref) => <CommandPrimitive.Empty ref={ref} className={cn('py-6 text-center text-[length:var(--text-xs)] text-[var(--muted-foreground)]', className)} {...props} />);
CommandEmpty.displayName = CommandPrimitive.Empty.displayName;
export const CommandGroup = React.forwardRef<React.ElementRef<typeof CommandPrimitive.Group>, React.ComponentPropsWithoutRef<typeof CommandPrimitive.Group>>(({ className, ...props }, ref) => <CommandPrimitive.Group ref={ref} className={cn('overflow-hidden p-1 text-[var(--foreground)] [&_[cmdk-group-heading]]:px-2 [&_[cmdk-group-heading]]:py-1.5 [&_[cmdk-group-heading]]:text-[length:var(--text-xs)] [&_[cmdk-group-heading]]:font-normal [&_[cmdk-group-heading]]:uppercase [&_[cmdk-group-heading]]:tracking-[0.14em] [&_[cmdk-group-heading]]:text-[var(--muted-foreground)]', className)} {...props} />);
CommandGroup.displayName = CommandPrimitive.Group.displayName;
export const CommandItem = React.forwardRef<React.ElementRef<typeof CommandPrimitive.Item>, React.ComponentPropsWithoutRef<typeof CommandPrimitive.Item>>(({ className, ...props }, ref) => <CommandPrimitive.Item ref={ref} className={cn('relative flex cursor-default select-none items-center gap-2 rounded-sm px-2 py-2 text-[length:var(--text-xs)] outline-none data-[disabled=true]:pointer-events-none data-[disabled=true]:opacity-40 data-[selected=true]:bg-[var(--accent)] data-[selected=true]:text-[var(--accent-foreground)]', className)} {...props} />);
CommandItem.displayName = CommandPrimitive.Item.displayName;
export const CommandSeparator = React.forwardRef<React.ElementRef<typeof CommandPrimitive.Separator>, React.ComponentPropsWithoutRef<typeof CommandPrimitive.Separator>>(({ className, ...props }, ref) => <CommandPrimitive.Separator ref={ref} className={cn('mx-1 h-px bg-[var(--border)]', className)} {...props} />);
CommandSeparator.displayName = CommandPrimitive.Separator.displayName;
export const CommandShortcut = ({ className, ...props }: React.HTMLAttributes<HTMLSpanElement>) => <span className={cn('ml-auto font-mono text-[length:var(--text-xs)] text-[var(--muted-foreground)]', className)} {...props} />;
