package com.aiclub.platform.service;

import org.h2.jdbcx.JdbcDataSource;
import org.junit.jupiter.api.Test;
import org.springframework.core.io.ClassPathResource;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.datasource.init.ResourceDatabasePopulator;

import java.nio.charset.StandardCharsets;
import java.util.UUID;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatCode;
import static org.assertj.core.api.Assertions.assertThatThrownBy;

/**
 * 校验 Flyway 迁移脚本在“全新库”和“历史库已执行旧版本迁移”两条路径上都能安全运行，
 * 避免仅通过改版本号修复重复编号后，又把已升级环境的启动过程重新打挂。
 */
class FlywayMigrationCompatibilityTests {

    /**
     * 新编号迁移对全新库仍然要保持可执行，
     * 并把历史 ai_model_config 记录补齐成 AUTO 默认模式。
     */
    @Test
    void shouldApplyOpenAiModeMigrationToFreshSchema() {
        JdbcDataSource dataSource = createDataSource("fresh");
        JdbcTemplate jdbcTemplate = new JdbcTemplate(dataSource);

        jdbcTemplate.execute("""
                CREATE TABLE ai_model_config (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY
                )
                """);
        jdbcTemplate.update("INSERT INTO ai_model_config DEFAULT VALUES");

        applyOpenAiModeMigration(dataSource);

        assertThat(jdbcTemplate.queryForObject(
                "SELECT openai_api_mode FROM ai_model_config WHERE id = 1",
                String.class
        )).isEqualTo("AUTO");
        assertThatThrownBy(() -> jdbcTemplate.update(
                "INSERT INTO ai_model_config (openai_api_mode) VALUES (?)",
                "LEGACY"
        )).isInstanceOf(Exception.class);
    }

    /**
     * 如果某些环境已经执行过旧的 V60 openai_api_mode 迁移，
     * 重新编号后的 V79 也必须能够安全跳过，而不是重复 ADD COLUMN / ADD CONSTRAINT。
     */
    @Test
    void shouldAllowRenumberedMigrationWhenLegacySchemaAlreadyContainsColumnAndConstraint() {
        JdbcDataSource dataSource = createDataSource("legacy");
        JdbcTemplate jdbcTemplate = new JdbcTemplate(dataSource);

        jdbcTemplate.execute("""
                CREATE TABLE ai_model_config (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    openai_api_mode VARCHAR(40) NOT NULL DEFAULT 'AUTO',
                    CONSTRAINT chk_ai_model_config_openai_api_mode
                        CHECK (openai_api_mode IN ('AUTO', 'RESPONSES', 'CHAT_COMPLETIONS', 'CHAT_COMPLETIONS_PLAIN'))
                )
                """);
        jdbcTemplate.update("INSERT INTO ai_model_config DEFAULT VALUES");

        assertThatCode(() -> applyOpenAiModeMigration(dataSource))
                .doesNotThrowAnyException();
        assertThat(jdbcTemplate.queryForObject(
                "SELECT openai_api_mode FROM ai_model_config WHERE id = 1",
                String.class
        )).isEqualTo("AUTO");
    }

    /** 主题偏好迁移应为历史账号补齐深海蓝默认值，保证旧账号登录后能正常返回主题。 */
    @Test
    void shouldBackfillDeepSeaThemeForExistingUsers() {
        JdbcDataSource dataSource = createDataSource("user_theme");
        JdbcTemplate jdbcTemplate = new JdbcTemplate(dataSource);

        jdbcTemplate.execute("""
                CREATE TABLE user_info (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    username VARCHAR(100) NOT NULL
                )
                """);
        jdbcTemplate.update("INSERT INTO user_info (username) VALUES (?)", "legacy-one");
        jdbcTemplate.update("INSERT INTO user_info (username) VALUES (?)", "legacy-two");

        applyThemePreferenceMigration(dataSource);

        assertThat(jdbcTemplate.queryForList("SELECT theme_id FROM user_info ORDER BY id", String.class))
                .containsExactly("deep-sea", "deep-sea");
    }

    private JdbcDataSource createDataSource(String scenario) {
        JdbcDataSource dataSource = new JdbcDataSource();
        dataSource.setURL("jdbc:h2:mem:flyway_openai_mode_" + scenario + "_" + UUID.randomUUID()
                + ";MODE=PostgreSQL;DB_CLOSE_DELAY=-1;DATABASE_TO_LOWER=TRUE");
        dataSource.setUser("sa");
        dataSource.setPassword("");
        return dataSource;
    }

    private void applyOpenAiModeMigration(JdbcDataSource dataSource) {
        new ResourceDatabasePopulator(
                false,
                false,
                StandardCharsets.UTF_8.name(),
                new ClassPathResource("db/migration/V79__ai_model_config_openai_api_mode.sql")
        ).execute(dataSource);
    }

    private void applyThemePreferenceMigration(JdbcDataSource dataSource) {
        new ResourceDatabasePopulator(
                false,
                false,
                StandardCharsets.UTF_8.name(),
                new ClassPathResource("db/migration/V120__user_theme_preference.sql")
        ).execute(dataSource);
    }
}
